image: node:7.10.1
options:
  max-time: 15
pipelines:
  default:
    - step:
        name: Build
        script:
          - cd ./functions
          - yarn
          - yarn build
  branches:
    master:
      - step:
          name: Build
          script:
            - cd ./functions
            - yarn
            - yarn build
          artifacts:
            - functions/**
      - step:
          name: Deploy to production
          deployment: production
          script:
            - yarn global add firebase-tools
            - firebase deploy --token $FIREBASE_TOKEN