image: node:7.10.1
options:
  max-time: 15
pipelines:
  default:
    - step:
        name: Build
        script:
          - cd ./functions
          - npm i
          - npm build
  branches:
    master:
      - step:
          name: Build
          script:
            - cd ./functions
            - npm i
            - npm build
          artifacts:
            - functions/**
      - step:
          name: Install deploy dependencies
          script:
            - npm i -g firebase-tools
          artifacts:
            - functions/**
      - step:
          name: Deploy to production
          script:
            - firebase deploy --token $FIREBASE_TOKEN